# **Demonstration of Numpy Commands**

In [ ]:
import numpy as np

# Float Array

In [ ]:
a=np.zeros(3)

In [ ]:
print("Array: ",a)

Array:  [0. 0. 0.]


In [ ]:
print("Type of array: ",type(a))

Type of array:  <class 'numpy.ndarray'>


In [ ]:
print("Type of array elements: ",type(a[0]))

Type of array elements:  <class 'numpy.float64'>


# **Int Array**

In [ ]:
b=np.zeros(3,int)

In [ ]:
print("Array: ",b)

Array:  [0 0 0]


In [ ]:
print("Type of array: ",type(b))

Type of array:  <class 'numpy.ndarray'>


In [ ]:
print("Type of array elements: ",type(b[0]))

Type of array elements:  <class 'numpy.int64'>


# **Various function on an array**

In [ ]:
z=np.zeros(10)

In [ ]:
print("Original Array: ", z)

Original Array:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print("Shape of Array: ", z.shape)
#tuple element ends with comma

Shape of Array:  (10,)


In [ ]:
z.shape=(10,1)

In [ ]:
print("New Array:")
z

New Array:


array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
print("Shape of New Array: ", z.shape)

Shape of New Array:  (10, 1)


# **Linspace Command**

In [ ]:
z=np.linspace(1,2,5)
print("Array created using linspace: ",z)

Array created using linspace:  [1.   1.25 1.5  1.75 2.  ]


In [ ]:
#positive index
print("Array elemnet at index 0: ",z[0])
print("Array elemnet at index 3: ",z[3])

Array elemnet at index 0:  1.0
Array elemnet at index 3:  1.75


In [ ]:
#slicing
print("Array elemnet at index 0 to 2: ",z[0:2])

Array elemnet at index 0 to 2:  [1.   1.25]


In [ ]:
#negative index
print("Array elemnet at index -1: ",z[-1])
print("Array elemnet at index -2: ",z[-3])

Array elemnet at index -1:  2.0
Array elemnet at index -2:  1.5


# **2-D Array**

In [ ]:
#identity matrix
i=np.identity(2,int)
print("Identity Matrix: ")
i

Identity Matrix: 


array([[1, 0],
       [0, 1]])

In [ ]:
#method 1 of creating matrix
z=np.zeros(4)
z.shape=(2,2)
print("2-D Array (method 1): ")
z

2-D Array (method 1): 


array([[0., 0.],
       [0., 0.]])

In [ ]:
#method 2 of creating matrix
y=np.array([[1,2],[3,4]])
print("2-D Array (method 2): ")
y

2-D Array (method 2): 


array([[1, 2],
       [3, 4]])

In [ ]:
#index
print("Element at index (0,1): ",y[0,1])
print("Element at index (0,0): ",y[0,0])

Element at index (0,1):  2
Element at index (0,0):  1


In [ ]:
#slicing
print("Element at index 0 to 1: ",y[0,:])
print("Element at index 1 to 1: ",y[1,:])
print("Element at index 0 to 0: ",y[:,0])
print("Element at index 1 to 0: ",y[:,1])

Element at index 0 to 1:  [1 2]
Element at index 1 to 1:  [3 4]
Element at index 0 to 0:  [1 3]
Element at index 1 to 0:  [2 4]


# **3-D Array**

In [ ]:
#creating a 3D array
H=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3-D Array: ")
H

3-D Array: 


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#index
print("Element at index (0,0): ",H[0,0])
print("Element at index (0,1): ",H[0,2])
print("Element at index (1,0): ",H[1,0])
print("Element at index (1,2): ",H[1,2])
print("Element at index (0,2): ",H[2,1])

Element at index (0,0):  1
Element at index (0,1):  3
Element at index (1,0):  4
Element at index (1,2):  6
Element at index (0,2):  8


In [ ]:
#slicing
print("Element at index 0 to 1: ",H[0,:])
print("Element at index 1 to 1: ",H[1,:])
print("Element at index 0 to 0: ",H[2,:])
print("Element at index 0 to 0: ",H[:,0])
print("Element at index 1 to 0: ",H[:,1])
print("Element at index 2 to 0: ",H[:,2])

Element at index 0 to 1:  [1 2 3]
Element at index 1 to 1:  [4 5 6]
Element at index 0 to 0:  [7 8 9]
Element at index 0 to 0:  [1 4 7]
Element at index 1 to 0:  [2 5 8]
Element at index 2 to 0:  [3 6 9]


# **Indices**

In [ ]:
x=np.linspace(2,4,5)
indices=np.array((0,2,3))

In [ ]:
print("Array: ",x)
print("Indices: ",indices)
print("Elements at indices: ",x[indices])

Array:  [2.  2.5 3.  3.5 4. ]
Indices:  [0 2 3]
Elements at indices:  [2.  3.  3.5]


# **Boolean**

In [ ]:
d=np.array([0,1,2,0,0],bool)
#every other number is true only 0 is false
print("Array: ",d)

Array:  [False  True  True False False]


# **Statistical Modelling**

In [ ]:
a=np.array((17,11,15,19,24,28,26,37,35,40))
a

array([17, 11, 15, 19, 24, 28, 26, 37, 35, 40])

In [ ]:
a.sort()
 #the changes will be refelected in the org array as well
print("Sorted Array: ")
a

Sorted Array: 


array([11, 15, 17, 19, 24, 26, 28, 35, 37, 40])

In [ ]:
print("Sum: ",a.sum())

Sum:  252


In [ ]:
print("Min: ",a.min())

Min:  11


In [ ]:
print("Max: ",a.max())

Max:  40


In [ ]:
print("Argmin: ",a.argmin())

Argmin:  0


In [ ]:
print("Argmax: ",a.argmax())

Argmax:  9


In [ ]:
print("Cumsum: ",a.cumsum())

Cumsum:  [ 11  26  43  62  86 112 140 175 212 252]


In [ ]:
print("Cumprod: ")
a.cumprod()

Cumprod: 


array([            11,            165,           2805,          53295,
              1279080,       33256080,      931170240,    32590958400,
        1205865460800, 48234618432000])

In [ ]:
print("Mean: ",a.mean())

Mean:  25.2


In [ ]:
print("Median: ",np.median(a))

Median:  25.0


In [ ]:
print("Variance: ",a.var())

Variance:  87.55999999999999


In [ ]:
print("Standard Deviation: ",a.std())

Standard Deviation:  9.357350052231668


In [ ]:
print("Searchsorted: ",a.searchsorted(25))

Searchsorted:  5


# **Operations on Array**

**1D Array**

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
print("Array a: ",a)
print("Array b: ",b)

Array a:  [1 2 3 4]
Array b:  [5 6 7 8]


In [ ]:
print("a+b: ",a+b)

a+b:  [ 6  8 10 12]


In [ ]:
print("a*b: ",a*b)

a*b:  [ 5 12 21 32]


In [ ]:
print("a+10: ",a+10)

a+10:  [11 12 13 14]


In [ ]:
print("a*10: ",a*10)

a*10:  [10 20 30 40]


**2D Array**

In [ ]:
A=np.ones((3,3))
B=np.ones((3,3))

In [ ]:
print("Array A: ")
print(A)
print("Array B: ")
print(B)

Array A: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array B: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print("A+B: ")
print(A+B)

A+B: 
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
print("A+10: ")
print(A+10)

A+10: 
[[11. 11. 11.]
 [11. 11. 11.]
 [11. 11. 11.]]


In [ ]:
X=np.array([[1,2,3],[4,5,6],[5,6,7]])
Y=np.array([[7,8,9],[4,8,9],[6,3,5]])

In [ ]:
X+Y

array([[ 8, 10, 12],
       [ 8, 13, 15],
       [11,  9, 12]])

In [ ]:
X+10

array([[11, 12, 13],
       [14, 15, 16],
       [15, 16, 17]])

In [ ]:
X @ Y #matrix multiplication

array([[ 33,  33,  42],
       [ 84,  90, 111],
       [101, 109, 134]])

In [ ]:
X.T #transpose

array([[1, 4, 5],
       [2, 5, 6],
       [3, 6, 7]])

In [ ]:
Z=np.array([2,3])
X=np.array([2,3])
X==Z

array([ True,  True])

In [ ]:
X[0]=5
X==Z

array([False,  True])